### ISSUE TITLE
No 'Access-Control-Allow-Origin' header in access calls

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#104]
`swellrt.org` is showing the following message:

> XMLHttpRequest cannot load http://demo.swellrt.org/swell/access/write/demo.swellrt.org/s+mCDtyYi9oeA/~/swl+root;sid=tqe0534sa26b1bkd6zawue0ev. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://swellrt.org' is therefore not allowed access. The response had HTTP status code 504.

**Comment by pablojan** [comment]
I've ran into this yesterday and it seems more likely a timeout problem.
Please check in the browser's network log the load time of that request.

2016-02-11 11:08 GMT+01:00 Antonio Tapiador <notifications@github.com>:

**Comment by atd** [comment]
I am trying to reproduce it, but the pad does not load in Chromium

It works ok in Iceweasel

**Comment by pablojan** [comment]
Ok, please check the requests to

 http://demo.swellrt.org/swell/access
<http://demo.swellrt.org/swell/access/write/demo.swellrt.org/s+mCDtyYi9oeA/%7E/swl+root;sid=tqe0534sa26b1bkd6zawue0ev>

I really think they are the problem.


2016-02-11 12:22 GMT+01:00 Antonio Tapiador <notifications@github.com>:

**Comment by atd** [comment]
```
GET /swell/access/write/demo.swellrt.org/s+mCDtyYi9oeA/~/swl+root;sid=tqe0534sa26b1bkd6zawue0ev HTTP/1.1
Host: demo.swellrt.org
Connection: keep-alive
Origin: http://swellrt.org
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Accept: */*
Referer: http://swellrt.org/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,es;q=0.6
Cookie: WSESSIONID=tqe0534sa26b1bkd6zawue0ev

HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Thu, 11 Feb 2016 12:07:25 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: http://swellrt.org
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: 
Cache-Control: no-store

{"waveId":"demo.swellrt.org/s+mCDtyYi9oeA","waveletId":"demo.swellrt.org/swl+root","canWrite":true,"canRead":true,"participantId":"_anonymous_tqe0534sa26b1bkd6zawue0ev@demo.swellrt.org"}
```

**Comment by pablojan** [comment]
@atd did you run into this issue during last week?

**Comment by atd** [comment]
It still takes about 30 seconds to respond to that request, pad loads after 1 minute (Chromium 47)

**Comment by pablojan** [comment]
Ok, I working on that, it's related with participation model and #156

2016-02-17 12:01 GMT+01:00 Antonio Tapiador <notifications@github.com>:

**Comment by pablojan** [comment]
Caused by the currently removed request access operation
