### ISSUE TITLE
Generate and add server.config dynamically for each docker image

### ISSUE THREAD

**Issue by pablojan** [P2Pvalue/swellrt#105]

**Comment by atd** [comment]
@pablojan please, could you point me to the right command?

**Comment by pablojan** [comment]
sure, the command is "ant gen-server-config" it will overwrite the previous
server.config file if it already exists


2016-02-17 13:29 GMT+01:00 Antonio Tapiador <notifications@github.com>:

**Comment by atd** [comment]
Ok, there are some differences with the config file we are using now:

Addresses are using `localhost` instead of `0.0.0.0`. This is needed for connecting from outside the docker container

`search_type` is set to `lucene` instead of `memory`

**Comment by pablojan** [comment]
good to know, i will change these values to the right ones

2016-02-17 15:31 GMT+01:00 Antonio Tapiador <notifications@github.com>:
