### ISSUE TITLE
org.apache.commons.configuration.ConfigurationException: The following required properties are missing from the server configuration: email_host, email_from_address

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#107]
In production, docker image 0.18.0-alpha

**Comment by atd** [comment]
This is quite weird, because in development dockers this error doesn't show up

**Comment by pablojan** [comment]
This is because the two missing properties configuring the email server.
Just add following stuff at the end of the server.config file, please set secure values for the environment:

```
# SMTP server host name
email_host = localhost

# Email address from which the system emails are sent
email_from_address = root@localhost

```

**Comment by atd** [comment]
I know, we talked about it and we agreed to make them optional. That's why I opened the issue.
