### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/gwt/i18n/client/Messages

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#114]
Aaaaaaaaaaaand.. another one!!

**Comment by pablojan** [comment]
F*** who has been added all this stuff????

2016-02-24 18:13 GMT+01:00 Antonio Tapiador <notifications@github.com>:

**Comment by atd** [comment]
Another one bites the dust:

`java.lang.NoClassDefFoundError: org/waveprotocol/box/server/authentication/i18n/PasswordRestoreMessages`

**Comment by atfornes** [comment]
Sorry, the missing dependencies had been included by my commit: https://github.com/P2Pvalue/swellrt/commit/0ae639c860fed41d7ac9e240c538b219d99487b8

there are three packages included in build.xml in that commit, I hope that is the last missing external class.

Regarding PasswordRestoreMessages, it is a new class in that commit, I am not sure why is not found.

**Comment by pablojan** [comment]
Probably that package org/waveprotocol/box/server/authentication/i18n is
not included in the package script either.

2016-02-24 18:39 GMT+01:00 atfornes <notifications@github.com>:

**Comment by atfornes** [comment]
@pablojan, @atd, I will check how to pack classes for my next code push. I can see this changes as an example, is there something else to do? how can we test that everything is packed before sharing our changes?

Thanks! and sorry for the issues :cry:

**Comment by atfornes** [comment]
Following classses has also been added in my commits:
`src/org/swellrt/server/box/servlet/PasswordServlet.java`
`src/org/waveprotocol/box/server/account/SecretToken.java `
`src/org/swellrt/server/box/servlet/EmailServlet.java`

but I understand that the following line https://github.com/P2Pvalue/swellrt/blob/a5ce4f85d3c1a9f19740ab06c7f663dea5d119a9/build.xml#L730 in build.xml already add them to the packaging, right?

**Comment by pablojan** [comment]
It should! :S please @atf could you fix the issue and push changes into
master. thanks

2016-02-24 19:10 GMT+01:00 atfornes <notifications@github.com>:

**Comment by atfornes** [comment]
ok, I will do it.

**Comment by atfornes** [comment]
@pablojan, is there any reason for src/org/waveprotocol/server to not be included in the packaging? should I refactor and move `org/waveprotocol/box/server/authentication/i18n/PasswordRestoreMessages` somewhere else?

**Comment by pablojan** [comment]
I would rather to move new classes in a swellrt's specific package, except
for stuff extending existing classes...
Packaging is controlled in the ant script, you should check it thoroughly.



2016-02-24 19:25 GMT+01:00 atfornes <notifications@github.com>:

**Comment by atfornes** [comment]
I believe that missing `java.lang.NoClassDefFoundError: org/waveprotocol/box/server/authentication/i18n/PasswordRestoreMessages`was due to broken dependency with com/google/gwt/i18n/client/Messages` since in build.xml file seems to be included and not excluded: https://github.com/P2Pvalue/swellrt/blob/master/build.xml#L727.

Please, reopen if it keeps failing. I do not know how to test that is working now without any dependency missing.

**Comment by atfornes** [comment]
also, @pablojan, should I mark a new version of SwellRT and push the tag?

**Comment by pablojan** [comment]
no, I will generate it a new one after pushing my changes


2016-02-24 19:46 GMT+01:00 atfornes <notifications@github.com>:
