### ISSUE TITLE
java.lang.NoClassDefFoundError: net/lightoze/gwt/i18n/client/LocaleFactory

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#116]
Will it have an end? :worried:

**Comment by pablojan** [comment]
This is even worst, a GWT client specific class, it shouldnt be in the
server part ever.

2016-02-25 11:27 GMT+01:00 Antonio Tapiador <notifications@github.com>:

**Comment by atfornes** [comment]
@pablojan, if you recall, I used a library to be able to translate as in GWT clients in the server. this is not used now and I will change the way translations are done. I will update a new tagged version with this fixed ASAP.

I am still looking for the good way to test if something else is broken... @pablojan, @atd, ideas wellcomed!

**Comment by atd** [comment]
@atfornes I am thinking about it, but the only thing it occurs to me is running the tests against the docker image. Of course, it only would discover errors if there are tests covering that part

**Comment by pablojan** [comment]
Apart from a automatic process to check integrity, rules are easy:

- If a .jar dependency is added to the project => add packages to .jar
build configuration (build-swellrt.xml dist-server)
- If a new java package is added to the project, add it (or check if
they're already included)  => add packages to .jar build configuration
(build-swellrt.xml dist-server)

2016-02-25 11:38 GMT+01:00 Antonio Tapiador <notifications@github.com>:
