### ISSUE TITLE
RuntimeException_1 {detailMessage: "Document had a mysterious sink.  Restoration is unsafe"

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#118]
I am getting this in the console when refreshing the window. @pablojan do you know what can be happening?

```
RuntimeException_1 {detailMessage: "Document had a mysterious sink.  Restoration is unsafe", stackTrace: Array[33]}
detailMessage: "Document had a mysterious sink.  Restoration is unsafe"
stackTrace: Array[33]
0: StackTraceElement_0
className_0: "Unknown"
fileName: "swellrt-0.js@116"
lineNumber: -1
methodName: "createStackTrace"
__proto__: seedTable.(anonymous function)
1: StackTraceElement_0
className_0: "Unknown"
fileName: "swellrt-0.js@13"
lineNumber: -1
methodName: "fillInStackTrace_2"
__proto__: seedTable.(anonymous function)
2: StackTraceElement_0
className_0: "Unknown"
fileName: "swellrt-0.js@109"
lineNumber: -1
methodName: "fillInStackTrace_0"
__proto__: seedTable.(anonymous function)
3: StackTraceElement_0
className_0: "Unknown"
fileName: "swellrt-0.js@3"
lineNumber: -1
methodName: "fillInStackTrace"
__proto__: seedTable.(anonymous function)
4: StackTraceElement_0
className_0: "Unknown"
fileName: "swellrt-0.js@8"
lineNumber: -1
methodName: "Throwable_1"
__proto__: seedTable.(anonymous function)
5: StackTraceElement_0
className_0: "Unknown"
fileName: "swellrt-0.js@15"
lineNumber: -1
methodName: "Exception_1"
__proto__: seedTable.(anonymous functioon)
6: StackTraceElement_0
className_0: "Unknown"
fileName: "swellrt-0.js@15"
lineNumber: -1
methodName: "RuntimeException_1"
__proto__: seedTable.(anonymous function)
7: StackTraceElement_0
className_0: "Unknown"
fileName: "swellrt-0.js@17"
lineNumber: -1
methodName: "$clearContent"
__proto__: seedTable.(anonymous function)
8: StackTraceElement_0
className_0: "Unknown"
fileName: "swellrt-0.js@3"
lineNumber: -1
methodName: "removeContentAndUnrender"
__proto__: seedTable.(anonymous function)
9: StackTraceElement_0
className_0: "Unknown"
fileName: "swellrt-0.js@17"
lineNumber: -1
methodName: "cleanUp"
__proto__: seedTable.(anonymous function)
10: StackTraceElement_0
className_0: "Unknown"
fileName: "swellrt-0.js@14"
lineNumber: -1
methodName: "jsWrapper.cleanUp"
__proto__: seedTable.(anonymous function)
11: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@18"
lineNumber: -1
methodName: "<anonymous>"
__proto__: seedTable.(anonymous function)
12: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@21"
lineNumber: -1
methodName: "eventHandler"
__proto__: seedTable.(anonymous function)
13: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@22"
lineNumber: -1
methodName: "jqLiteRemoveData"
__proto__: seedTable.(anonymous function)
14: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@7"
lineNumber: -1
methodName: "jqLiteDealoc"
__proto__: seedTable.(anonymous function)
15: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@18"
lineNumber: -1
methodName: "jqLiteRemove"
__proto__: seedTable.(anonymous function)
16: StackTraceElement_0
className_0: "Unknown"
fileName: "@-1"
lineNumber: -1
methodName: "JQLite."
__proto__: seedTable.(anonymous function)
17: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@19"
lineNumber: -1
methodName: "anonymous"
__proto__: seedTable.(anonymous function)
18: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@7"
lineNumber: -1
methodName: "options.domOperation"
__proto__: seedTable.(anonymous function)
19: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@19"
lineNumber: -1
methodName: "close"
__proto__: seedTable.(anonymous function)
20: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@9"
lineNumber: -1
methodName: "closeAndReturnNoopAnimator"
__proto__: seedTable.(anonymous function)
21: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@16"
lineNumber: -1
methodName: "init"
__proto__: seedTable.(anonymous function)
22: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@22"
lineNumber: -1
methodName: "prepareRegularAnimation"
__proto__: seedTable.(anonymous function)
23: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@13"
lineNumber: -1
methodName: "initDriverFn"
__proto__: seedTable.(anonymous function)
24: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@24"
lineNumber: -1
methodName: "invokeFirstDriver"
__proto__: seedTable.(anonymous function)
25: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@31"
lineNumber: -1
methodName: "triggerAnimationStart"
__proto__: seedTable.(anonymous function)
26: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@13"
lineNumber: -1
methodName: "anonymous"
__proto__: seedTable.(anonymous function)
27: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@20"
lineNumber: -1
methodName: "forEach"
__proto__: seedTable.(anonymous function)
28: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@9"
lineNumber: -1
methodName: "anonymous"
__proto__: seedTable.(anonymous function)
29: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@36"
lineNumber: -1
methodName: "$digest"
__proto__: seedTable.(anonymous function)
30: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@24"
lineNumber: -1
methodName: "$apply"
__proto__: seedTable.(anonymous function)
31: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@23"
lineNumber: -1
methodName: "<anonymous>"
__proto__: seedTable.(anonymous function)
32: StackTraceElement_0
className_0: "Unknown"
fileName: "http://localhost:8000/js/app.min.js@21"
lineNumber: -1
methodName: "eventHandler"
__proto__: seedTable.(anonymous function)
```

**Comment by pablojan** [comment]
Hard to say without more research, but it might be that the editor or doc used after refresh hasn't been properly initialised again. I will try to reproduce. Do you load again all swellrt stuff in the refresh?

El 2/3/2016 3:36 p. m., Antonio Tapiador <notifications@github.com> escribió:

I am getting this in the console when refreshing the window. @pablojan do you know what can be happening?

RuntimeException_1 {detailMessage: "Document had a mysterious sink. Restoration is unsafe", stackTrace: Array[33]} detailMessage: "Document had a mysterious sink. Restoration is unsafe" stackTrace: Array[33] 0: StackTraceElement_0 className_0: "Unknown" fileName: "swellrt-0.js@116" lineNumber: -1 methodName: "createStackTrace" __proto__: seedTable.(anonymous function) 1: StackTraceElement_0 className_0: "Unknown" fileName: "swellrt-0.js@13" lineNumber: -1 methodName: "fillInStackTrace_2" __proto__: seedTable.(anonymous function) 2: StackTraceElement_0 className_0: "Unknown" fileName: "swellrt-0.js@109" lineNumber: -1 methodName: "fillInStackTrace_0" __proto__: seedTable.(anonymous function) 3: StackTraceElement_0 className_0: "Unknown" fileName: "swellrt-0.js@3" lineNumber: -1 methodName: "fillInStackTrace" __proto__: seedTable.(anonymous function) 4: StackTraceElement_0 className_0: "Unknown" fileName: "swellrt-0.js@8" lineNumber: -1 methodName: "Throwable_1" __proto__: seedTable.(anonymous function) 5: StackTraceElement_0 className_0: "Unknown" fileName: "swellrt-0.js@15" lineNumber: -1 methodName: "Exception_1" __proto__: seedTable.(anonymous functioon) 6: StackTraceElement_0 className_0: "Unknown" fileName: "swellrt-0.js@15" lineNumber: -1 methodName: "RuntimeException_1" __proto__: seedTable.(anonymous function) 7: StackTraceElement_0 className_0: "Unknown" fileName: "swellrt-0.js@17" lineNumber: -1 methodName: "$clearContent" __proto__: seedTable.(anonymous function) 8: StackTraceElement_0 className_0: "Unknown" fileName: "swellrt-0.js@3" lineNumber: -1 methodName: "removeContentAndUnrender" __proto__: seedTable.(anonymous function) 9: StackTraceElement_0 className_0: "Unknown" fileName: "swellrt-0.js@17" lineNumber: -1 methodName: "cleanUp" __proto__: seedTable.(anonymous function) 10: StackTraceElement_0 className_0: "Unknown" fileName: "swellrt-0.js@14" lineNumber: -1 methodName: "jsWrapper.cleanUp" __proto__: seedTable.(anonymous function) 11: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@18" lineNumber: -1 methodName: "<anonymous>" __proto__: seedTable.(anonymous function) 12: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@21" lineNumber: -1 methodName: "eventHandler" __proto__: seedTable.(anonymous function) 13: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@22" lineNumber: -1 methodName: "jqLiteRemoveData" __proto__: seedTable.(anonymous function) 14: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@7" lineNumber: -1 methodName: "jqLiteDealoc" __proto__: seedTable.(anonymous function) 15: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@18" lineNumber: -1 methodName: "jqLiteRemove" __proto__: seedTable.(anonymous function) 16: StackTraceElement_0 className_0: "Unknown" fileName: "@-1" lineNumber: -1 methodName: "JQLite." __proto__: seedTable.(anonymous function) 17: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@19" lineNumber: -1 methodName: "anonymous" __proto__: seedTable.(anonymous function) 18: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@7" lineNumber: -1 methodName: "options.domOperation" __proto__: seedTable.(anonymous function) 19: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@19" lineNumber: -1 methodName: "close" __proto__: seedTable.(anonymous function) 20: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@9" lineNumber: -1 methodName: "closeAndReturnNoopAnimator" __proto__: seedTable.(anonymous function) 21: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@16" lineNumber: -1 methodName: "init" __proto__: seedTable.(anonymous function) 22: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@22" lineNumber: -1 methodName: "prepareRegularAnimation" __proto__: seedTable.(anonymous function) 23: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@13" lineNumber: -1 methodName: "initDriverFn" __proto__: seedTable.(anonymous function) 24: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@24" lineNumber: -1 methodName: "invokeFirstDriver" __proto__: seedTable.(anonymous function) 25: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@31" lineNumber: -1 methodName: "triggerAnimationStart" __proto__: seedTable.(anonymous function) 26: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@13" lineNumber: -1 methodName: "anonymous" __proto__: seedTable.(anonymous function) 27: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@20" lineNumber: -1 methodName: "forEach" __proto__: seedTable.(anonymous function) 28: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@9" lineNumber: -1 methodName: "anonymous" __proto__: seedTable.(anonymous function) 29: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@36" lineNumber: -1 methodName: "$digest" __proto__: seedTable.(anonymous function) 30: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@24" lineNumber: -1 methodName: "$apply" __proto__: seedTable.(anonymous function) 31: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@23" lineNumber: -1 methodName: "<anonymous>" __proto__: seedTable.(anonymous function) 32: StackTraceElement_0 className_0: "Unknown" fileName: "http://localhost:8000/js/app.min.js@21" lineNumber: -1 methodName: "eventHandler" __proto__: seedTable.(anonymous function)

**Comment by atd** [comment]
Ok, it probably has to do with the way I am using angular in some point of the redesign. I will take a workaround

Thank you for the feedback
