### ISSUE TITLE
Avatar absolute URLs are malformed

### ISSUE THREAD

**Issue by llopv** [P2Pvalue/swellrt#120]
I saw this some time ago, but I didn't remember to report it.

As you can see, `swell/account/{nick}/` is repeated.

![captura de pantalla de 2016-03-06 16-36-05](https://cloud.githubusercontent.com/assets/16879027/13555183/c537405c-e3b9-11e5-9bcb-49e8621a3e78.png)

**Comment by pablojan** [comment]
What swellrt's version are you using? It should be fixed in newest release.

2016-03-06 16:39 GMT+01:00 David Llop <notifications@github.com>:

**Comment by llopv** [comment]
The same error is occurring with `0.25.2-alpha`.

**Comment by pablojan** [comment]
Fix Ready in 0.26.0-alpha
