### ISSUE TITLE
Cannot restore mongodb from backup

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#122]
After using `mongobackup` and `mongorestore` on `wiab` mongo db, I get lots of

```
- E11000 duplicate key error collection: wiab.deltas index: _id_ dup key: { : ObjectId('56ddc075e4b0996f4ac0c636') }
```

**Comment by pablojan** [comment]
It seems the target db is not empty and it has already these _id_'s.
Does it make sense to empty the target db before?


2016-03-07 20:08 GMT+01:00 Antonio Tapiador <notifications@github.com>:

**Comment by atd** [comment]
I am afraid it doesn't. I tried both with `mongorestore --drop` and manually dropping the database in mongo with `db.wiab.dropDatabase()`

**Comment by pablojan** [comment]
That makes me think that current db has duplicated ids (¿?), I am trying to
figure out why...

(here some refs to investigate...)
http://stackoverflow.com/questions/11241819/duplicate-documents-on-id-in-mongo
http://stackoverflow.com/questions/4677237/possibility-of-duplicate-mongo-objectids-being-generated-in-two-different-colle

2016-03-08 9:20 GMT+01:00 Antonio Tapiador <notifications@github.com>:

**Comment by kevinleeTCA** [comment]
Do not drop the database
I guess you need to drop the collections that has duplications, which actually works for me.
For example, if the collection "users" got duplication error when running backup.
then in mongo shell, you can run
`db.users.drop()`
and redo the backup again, it will work
