### ISSUE TITLE
Serve images using https

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#127]
`Mixed Content: The page at 'https://app.teem.works/#/communities/cHJvdG90eXBlLnAycHZhbHVlLmV1L3MrdmFzamZYdEM1TkE' was loaded over HTTPS, but requested an insecure image 'http://swellrt.teem.works/swell/account/sem/avatar/c2VtQHByb3RvdHlwZS5wMnB2YWx1ZS5ldQ_1457610823720.png'. This content should also be served over HTTPS.`

**Comment by pablojan** [comment]
Does the nginx proxy send requests to swellrt server in HTTP or HTTPS? 
This could be spoiling the URL building.

**Comment by atd** [comment]
Yes, but shouldn't it be spoiling the host and port as well?

**Comment by pablojan** [comment]
I am not sure what nginx is doing. But SwellRT is taken scheme, host and port from the request.

I've found this http://stackoverflow.com/questions/19598690/how-to-get-host-name-with-port-from-a-http-or-https-request

We could try to set those headaers. I am coding a patch that will check it

**Comment by atd** [comment]
Ok, nginx is passing the Host header

I have added the X-Forwarded-Proto header

Thank you Pablo!
