### ISSUE TITLE
SwellRT gets stuck when loading a wave (Teem)

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#132]
![image](https://cloud.githubusercontent.com/assets/26228/14281116/7aae0c9c-fb37-11e5-9ff2-9d723c654379.png)

Note that the websocket is opened (still receiving pings) but there is not response to `ProtocolAuthenticate` and `ProtocolOpenRequest` messages

This time I am not logged in teem, it also happens when logged in

**Comment by atd** [comment]
I can't open any wave

Logging in fixes the issue

**Comment by pablojan** [comment]
Thanks, Looking into!

2016-04-05 14:10 GMT+02:00 Antonio Tapiador <notifications@github.com>:

**Comment by pablojan** [comment]
Probably a session issue fixed in https://github.com/P2Pvalue/swellrt/releases/tag/v0.28.4-alpha
