### ISSUE TITLE
Uncaught TypeError: Cannot read property '-webkit-user-modify' of undefined

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#151]
1. Add a need widget
2. Leave the teem (open the editor as read only)

![image](https://cloud.githubusercontent.com/assets/26228/15106122/6667f0e0-15c7-11e6-85b5-3225e8575bae.png)

**Comment by pablojan** [comment]
It seems the widget throws that error when the editor goes to read only state

**Comment by pablojan** [comment]
@atd I can't reproduce in my local env. Can you send me the DOM's picture of your widget or deploy it on stagging

**Comment by atd** [comment]
Sure! Deploying..

**Comment by pablojan** [comment]
Checking out staging with Firefox I can see...

When I click the checkbox to mark it as complete console shows an erro:

```
Error: event is not defined
.controller</e.toggleCompleted@https://staging.teem.works/js/app.min.js:28:4887
anonymous/fn@https://staging.teem.works/js/app.min.js line 9 > Function:2:430
t@https://staging.teem.works/js/app.min.js:7:13913
rs[t]</<.compile/</</r@https://staging.teem.works/js/app.min.js:9:26063
xi/this.$get</p.prototype.$eval@https://staging.teem.works/js/app.min.js:7:23794
xi/this.$get</p.prototype.$apply@https://staging.teem.works/js/app.min.js:7:24026
rs[t]</<.compile/</<@https://staging.teem.works/js/app.min.js:9:26113
Q.event.dispatch@https://staging.teem.works/js/app.min.js:2:19251
Q.event.add/m.handle@https://staging.teem.works/js/app.min.js:2:16061
```

When I leave the teem this exception is thrown and I can't see editor's context:

```
uncaught exception: Class$S40: Couldn't get the 'contentEditable' attribute for element '[object Comment]' tag name = undefined
```

**Comment by pablojan** [comment]
Confirmed issue on Chrome:

When I enter the teem not being a participant I can't see the pad's text.
After join the teem, I refresh the teem and now I can see the pad's text.
When I leave then the teem, `TypeError: Cannot read property '-webkit-user-modify' of undefined` exception is thrown and I can't see pad's text.

**Comment by atd** [comment]
Fixed the first error and deploying to staging

The second one seems to be related with the one in chrome. It seems like the widget content is not painted

**Comment by pablojan** [comment]
Caused by a race condition, angular directive (widget) is not completely rendered before attaching it to the editor.
