### ISSUE TITLE
On widget added to editor return a reference to DOM element

### ISSUE THREAD

**Issue by pablojan** [P2Pvalue/swellrt#152]
On widget added to editor return a reference to the widget first DOM element

**Comment by atd** [comment]
addWidget method returns `undefined`

**Comment by llopv** [comment]
Use `...Closes #issue...` or `...Fixes #issue...` instead of `...Implements #issue...` to close github issues automatically.

**Comment by atd** [comment]
It is not closed! See my previous comment

**Comment by pablojan** [comment]
Weird, code seems ok... could you provide a snapshot of the widget's DOM?
thanks

2016-05-10 10:40 GMT+02:00 Antonio Tapiador <notifications@github.com>:
