### ISSUE TITLE
Remove contenteditable and -webkit-user-modify from widgets

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#154]
`contenteditable` and `-webkit-user-modify` css options let users remove html content from widget (not only the text, but also the checkbox in the case of teem needs)

Developers can always add those options using the widget `sw-widget[-*]` classes

**Comment by atd** [comment]
It is also affecting CSS in new versions of chrome https://github.com/P2Pvalue/teem/issues/273

**Comment by llopv** [comment]
It is still happening.

**Comment by pablojan** [comment]
Do you mean that these styles are still rendered?

2016-08-25 17:03 GMT+02:00 David Llop <notifications@github.com>:

**Comment by llopv** [comment]
`-webkit-user-modify` in need widgets has disappeared, but it still remains in editor's first div. You should remove it too.

**Comment by atfornes** [comment]
:smile: thanks
