### ISSUE TITLE
Duplicate tab in browsers generate bad session

### ISSUE THREAD

**Issue by pablojan** [P2Pvalue/swellrt#155]
When an user duplicates a tab, the sessionStorage object is duplicated, keeping the same value for sessionStorage['x-swellrt-window-id']. This causes the server to handle the same connection for both tabs and the non last tab loose the connection.

Suggested solution: to calculate the value sessionStorage['x-swellrt-window-id'] everytime the page is loaded. This impacts the feature of automatic login, that now could autologin the client with the last user having the same http session (despite its window id)

**Comment by atd** [comment]
@pablojan why do you need to store the window id? If you just keep it in memory, it will last until the window is closed

**Comment by pablojan** [comment]
Awesome!
