### ISSUE TITLE
Pad editions lost after session change

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/swellrt#160]
After changing a session from ANONYMOUS to a named one with the following steps, the changes performed in the pad are **not saved** and there are no Exceptions or other way to detect those losses.

````javascript
SwellRT.logout()
SwellRT.startSession(
  'http://<swell_server.net>',
   '<user_name>', 
  '<user_password>', 
  function(s){console.log('success:', s)},
  function(s){console.log('error:', s)})
```

A success is received form the last cal with the session object

**Comment by pablojan** [comment]
Not an issue.
Collab. objects must be reopened anytime a session is started

https://github.com/P2Pvalue/swellrt/wiki/Sessions-and-Users
