### ISSUE TITLE
SwellRT.events.DATA_STATUS_CHANGED is not triggered on pad edition

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#167]
Steps to reproduce (in Teem):

* Insert `console.dir(data)` inside teem's callback, just before line https://github.com/P2Pvalue/teem/blob/master/src/js/services/sessionService.js#L59
* Pause docker swellrt container with `docker pause teem-swellrt`
* Edit the pad

No data appears in the console. I will expect the callback to be fired with each pad edition

**Comment by pablojan** [comment]
It can't be reproduced in a standalone SwellRT test env. It could be related with #166 : only one handler for the event was supported.
