### ISSUE TITLE
Version in wave.conf of last release is incorrect

### ISSUE THREAD

**Issue by Akronix** [P2Pvalue/swellrt#180]
Hello!

I've downloaded the tar ball with the last release of swellRT (https://github.com/P2Pvalue/swellrt/releases/latest) and I've tried to run the server but it doesn't work because it's trying to find version 0.51.0-alpha since `config/wave.conf` says `version=0.51.0-alpha`.

If replaced 0.51.0-alpha in `config/wave.conf` by 0.52.0-alpha and now it works.

**Comment by pablojan** [comment]
Thanks Abel. We are about to publish a new release, we will use the right
version then

2016-08-27 21:21 GMT+02:00 Abel Serrano Juste <notifications@github.com>:

**Comment by llwp** [comment]
@pablojan we have 9 releases since this date - does this item need to be closed?

@Akronix can you let us know if your issue is resolved?

Thanks, folks!

**Comment by atfornes** [comment]
You are right @llwp. This issue is old.
