### ISSUE TITLE
Support https for swellrt.org

### ISSUE THREAD

**Issue by Akronix** [P2Pvalue/swellrt#185]
Hi!

I'm having problems to deploy [my app: upvote](https://github.com/Akronix/upvote) to gh-pages .
It has an Mixed content error since I'm using the SwellRT server hosted in demo.swellrt.org

Could you please support https for swellrt.org?

**Comment by pablojan** [comment]
We are not planning in the short term to add support for HTTPS in our demo server (demo.swellrt.org).
As solution, we use gh-pages with no HTTPS  in our demo http://p2pvalue.github.io/swellrt/pad/

Is it fully mandatory to use https in your app?

**Comment by atfornes** [comment]
@pablojan, even if it is not planned to be resolved soon, I believe the issue should keep opened.

I think it is something that will facilitate the development with SwellRT, which is something we are looking for.
