### ISSUE TITLE
Support for node

### ISSUE THREAD

**Issue by Akronix** [P2Pvalue/swellrt#186]
In nodejs, If I try to load swellrt using http.get to demo.swellrt.org I get the following error:

```
remote_modules/swellrt.js:8
window.SwellRT = {
^

ReferenceError: window is not defined
```
maybe it's possible to place SwellRT object in somewhere else so that nodejs apps can use it?

**Comment by pablojan** [comment]
A nodejs compatible version of SwellRT JS library is not planned in the short term. 
I am afraid that JS library relies in several browser specific APIs so port for NodeJS is not easy and fast.

**Comment by atfornes** [comment]
A list if the browser specific libraries would be appreciated in this issue. That list would facilitate to add support to node.js by interested developers, even if that is not planned soon in SwellRT current roadmap.
