### ISSUE TITLE
Current javascript is not minimized / gziped

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#193]
Current js is at http://demo.swellrt.org/swellrt/F4E375C09311C6E15FAE874378E51EAE.cache.js

Current size: 3.4 MB

**Comment by pablojan** [comment]
Fixed in v0.55.1-alpha
Actually the fix is to change jenkins build config from:

`./gradlew clean jar compileJsWebDev test createDistBin`

to

`./gradlew clean jar compileJsWeb test createDistBin`
