### ISSUE TITLE
Sessions are broken (?)

### ISSUE THREAD

**Issue by llopv** [P2Pvalue/swellrt#199]
When I log in and refresh the window, the session is lost (in Teem).

**Comment by llopv** [comment]
It only happens to me. @atd can't reproduce it, maybe it happens because of cookies?

**Comment by pablojan** [comment]
Sessions cant be resumend if browser has disabled 3rd party cookies.
Please, could you check that? thanks

2016-10-25 11:28 GMT+02:00 David Llop <notifications@github.com>:

**Comment by pablojan** [comment]
@llopv please, could you check again that 3rd party cookies confing in your box? thanks

**Comment by pablojan** [comment]
Couldn't be reproduced in alpha version.
