### ISSUE TITLE
SwellRT connection fails after web sockets upgrade GET call

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/swellrt#20]
After a web socket connection upgrade, the SwellRT connection fails and the events such as  as SwellRT.events.ITEM_ADDED, ITEM_REMOVED and ITEM_CHANGED are not received:

This can be reproduced with P2Pvalue/swellrt-showcase connecting to an external wave server such as wave.p2pvalue.eu:

1. Connect to the same wave id in two browser tabs/windows
2. add some items to the list and see that it works as expected
3. wait until a socket upgrade GET call is done (for instance in network tab o firebug)
4. the tab/window where the GET call has been done is no longer updated with new additions to the list (i.e. the model changed events such as SwellRT.events.ITEM_ADDED, ITEM_REMOVED and ITEM_CHANGED are not received.)
 
-----------
See related issue P2Pvalue/pear2pear#20

**Comment by pablojan** [comment]
I didn't need to open the same Wave from two different browser tabs or
windows. From a single tab, after a while, the socket upgrade request is
received and connection to the server is lost.


2015-06-01 18:47 GMT+02:00 atfornes <notifications@github.com>:

**Comment by pablojan** [comment]
See https://github.com/P2Pvalue/swellrt/issues/25
