### ISSUE TITLE
Pad error on Mac: StringMap/StringSet cannot contain null keys

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#200]
This error shows on Chrome 54 on Mac, when typing on the pad, in this project 

https://app.teem.works/teems/cHJvdG90eXBlLnAycHZhbHVlLmV1L3MrdXZYdEdUdHozY0E?tab=pad

![image](https://cloud.githubusercontent.com/assets/26228/19798394/19f4ee1e-9cf1-11e6-9979-3889f5254c20.png)

**Comment by pablojan** [comment]
Thanks for the very detailed trace!

**Comment by pablojan** [comment]
Casued by deprecated and non-standard stuff: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyIdentifier

**Comment by pablojan** [comment]
https://groups.google.com/a/chromium.org/forum/#!topic/input-dev/aLDdnHSMbFU
