### ISSUE TITLE
Missing editor API functions

### ISSUE THREAD

**Issue by llopv** [P2Pvalue/swellrt#208]
- [ ] `editor.getRange()`
- [ ] `editor.getAnnotations()`
- [ ] `editor.clearAnnotation('paragraph')` (`editor.clearAnnotation('style')` is working)

In addition, we should merge functions like `setAnnotation()` and `setAnnotationInRange()` in one.

**Comment by pablojan** [comment]
Latest version  of editor component has cover this point (beta, master branch)
