### ISSUE TITLE
Connection to SwellRT error

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/swellrt#21]
Using P2Pvalue/swellrt-showcase and current version of SwellRT (efec826), the connection seams to have problems:

Data is not sent to the server, being the info message of the form `Sending data... (0/8/8)`

I am not sure if it is related but, when refreshing, an atmosphere error is shown in console:
`InvalidAccessError: A parameter or an operation is not supported by the underlying object`

**Comment by pablojan** [comment]
See https://github.com/P2Pvalue/swellrt/issues/25
