### ISSUE TITLE
As user, i need to see what i´m comment on the tasks

### ISSUE THREAD

**Issue by elenamv** [P2Pvalue/swellrt#212]
The field is so little that the text dessappears
Also, the send button have to change to green when i start to write.
It is a good time to change when we integrate the tasks in the pad, @llopv :)

![captura de pantalla 2016-12-13 a las 10 29 04](https://cloud.githubusercontent.com/assets/16928147/21134813/cc28617c-c11f-11e6-9220-09d6253f0921.png)

**Comment by pablojan** [comment]
Hey @elenamv , this issue seems to impact Teem, but this is the SwellRT repo...
Are you doing right?

**Comment by elenamv** [comment]
Definitely not!! :P
Github is hard for me! I'll see if I can change it
