### ISSUE TITLE
Several issues related to List

### ISSUE THREAD

**Issue by ngwaitat** [P2Pvalue/swellrt#224]
1. Create a List, then create a Map and add it to the List, any modification to the Map's property will then throw an exception. If I change to put a Map as a property of another Map, then no problem.

2. The indexOf() method of List always returns -1.

3. This not necessarily an issue but a suggestion - currently no insert() method available to List, I'll have to clear all and re-add all items, so it would be good to have this method.

**Comment by pablojan** [comment]
Thank you for reporting this issue. I am working in a fix to be delivered
asap.

2017-11-18 5:14 GMT+01:00 ngwaitat <notifications@github.com>:

**Comment by ngwaitat** [comment]
Great, thanks. :+1:

**Comment by pablojan** [comment]
Hi @ngwaitat, after looking into your issues, I couldn't reproduce any of them. I am not sure if there was some misunderstood with the provided documentation. Next I write down  some examples  and I give you some hints... In any case, your issues have gave me a chance to review the api again and fix some minor issues. Thank you very much, and please contact me for any other question or suggestion.

Please, check how you have created maps and list. There is a big difference whether you create a Swell map or list with create() methods:

```
obj.node('list').add(swell.Map.create());
obj.node('list').add(swell.List.create());
```

or you creates Javascript objects and arrays:

```
obj.node('list').add({ a: "x", b: "y" });
obj.node('list').add([ a, b, c]);
```

in the second form, SwellRT handles the JS map or array as a whole object, storing it as JSON internally. You can't make changes to inner properties nor listen for changes. You have to replace the whole object in order to do an update.

However, in order to initialize Swell maps and lists with Javascript syntax, create() method has an extended syntax:

```
obj.node('list').add(swell.Map.create({ a: "x", b: "y" }));
obj.node('list').add(swell.List.create([ a, b, c]));
```


> Create a List, then create a Map and add it to the List, any modification to the Map's property will then throw an exception. If I change to put a Map as a property of another Map, then no problem.

See some examples:

```
// run this with ./gradlew serverlessRun

var service = swell.runtime.get();
var obj = service.open("o1");

obj.set("list", swell.List.create());
obj.node("list").add(swell.Map.create()); 
obj.node("list.0").set("p1", "value 1");	
obj.node("list.0").set("p2", 2);
obj.node("list.0").set("p3", true);

obj.node("list").add("x");
obj.node("list").add("y");

// modify properties of the map inside the list
// update map property
obj.set("list.0.p2", 20); // same as -> obj.node("list").pick(0).set("p2", 20);
// remove map property
obj.delete("list.0.p2");

// remove list item
obj.node("list").remove(2); // remove 'y', same as -> obj.delete("list.2");

```

> The indexOf() method of List always returns -1.

indexOf only works for nodes:

```
var n2 = obj.node("list.2");
obj.node("list").indexOf(n2); // returns 2
``` 

> This not necessarily an issue but a suggestion - currently no insert() method available to List, I'll have to clear all and re-add all items, so it would be good to have this method.

Three methods are provided to add elements to a swell list `push(path, value) / add(value) / addAt(value, index)`

**Comment by ngwaitat** [comment]
Thanks Pablo. When trying to repeat the list/map problem, I found a new bug, this is the complete code to repeat the problem:

			var createLoginInfo = function() {
				return {
					id: swellrt.Constants.ANONYMOUS_USER_ID,
					password: ''
				};
			};
			
			var createOpenObjInfo = function() {
				return {
					// Increate id to test a new object.
					id: '001'
				};
			};
			
			var createMap = function() {
				var result = swellrt.Map.create();
				
				result.set('name', 'm1');
				
				return result;
			};
			
			var createList = function() {
				var result = swellrt.List.create();
				
				result.add(createMap());
				
				return result;
			};
			
			var objOpened = function(obj) {
				var l1;
				var m1;
				
				if (obj.get('inited') !== true) {
					obj.set('inited', true);
					
					obj.setPublic(true);

					l1 = createList();
					obj.set('l1', 11);
					
					console.log(l1.pick(0).get('name'));
					
				} else {
					l1 = obj.node('l1');					
					console.log(l1.pick(0).get('name'));
				}
			};
			
			
			
			var serviceLoggedIn = function(service) {
				var openobjInfo = createOpenobjInfo();

				service.open(openobjInfo)
					.then(obj => {
						objOpened(obj);
					})
					.catch(error => {
						alert(error);
					});
			};
			
			
			swellrt.onReady(service => {
				console.log
				var loginInfo = createLoginInfo();
				
				service.login(loginInfo)
					.then(profile => {
						serviceLoggedIn(service); 
					})
					.catch(error => {
						alert(error);
					});        
			});

The problem is, when I load the saved object, the call to pick() will fail since there is no pick() method for the loaded list l1. Any idea why the loaded l1 is not the same list structure as it was created? Thanks.

**Comment by pablojan** [comment]
Obviously that is a bug, but I couldn't reproduce it in my latest version.
Which version are you using?

2017-11-28 11:12 GMT+01:00 ngwaitat <notifications@github.com>:

**Comment by ngwaitat** [comment]
It is 1.0.3-beta.

**Comment by pablojan** [comment]
Let me check again but I used that version this morning. 




El 4 dic. 2017 16:27, ngwaitat <notifications@github.com> escribió:

It is 1.0.3-beta.
