### ISSUE TITLE
Possibility of managing users in server side?

### ISSUE THREAD

**Issue by ngwaitat** [P2Pvalue/swellrt#226]
In this documentation we know how to manage users using JavaScript API:

https://github.com/P2Pvalue/swellrt/wiki/Working-with-users

But is it possible to do the same things in server side? Thank you.

**Comment by pablojan** [comment]
Sorry, at this moment the SwellRT server doesn't provide an administrative
console. That is a future feature.

2017-11-29 2:57 GMT+01:00 ngwaitat <notifications@github.com>:

**Comment by ngwaitat** [comment]
I see, thank you very much.
