### ISSUE TITLE
Memory leaking

### ISSUE THREAD

**Issue by haraldjordan78** [P2Pvalue/swellrt#236]
Hey, i am currently testing swellrt on windows, compiled prod and using gradlew run to start as background service. 
I see the memory consumption of java process growing every day (without using any function of the server). After around 3 days it gets slightly more than 1GB and therefore Memory problems using java default config.

Am i doing something wrong, is it different running the stuff as docker?

**Comment by pablojan** [comment]
Hi! thanks so much for reporting this. At a glance I guess it is a memory leak in the code. I am going to look into it asap. There is no difference in config whether you run it in docker or not. Please, let me know if you get further symptoms.

**Comment by haraldjordan78** [comment]
This is the error message i got at a client after a few days idle server and then about 1 hour testing (not much) at the client:
![swell](https://user-images.githubusercontent.com/34220041/38054214-9a50df24-32d6-11e8-9a22-1bf4afbb14fc.png)

I'll try to start the java vm with remote jmx enabled in order to do memory dumps in the next days.

**Comment by haraldjordan78** [comment]
moved to https://github.com/P2Pvalue/swellrt/issues/243
