### ISSUE TITLE
Maximum number of Clients (viewers) for Text editor

### ISSUE THREAD

**Issue by haraldjordan78** [P2Pvalue/swellrt#238]
Hey there!
before i go for empherical testing, could you please indicate what is the maximum thinkable number of attendents to an editor? I am investigating the options to have let us say 1000+ viewers and 2 editors for the same text document at a time. 
What would i need to do to support at least 1000 viewers on the same document without adding too much latency in receiving the latest modifications to the document, just add lots of cpu and ram to the host and modify the java vm options accordingly? :-)

**Comment by haraldjordan78** [comment]
...if nobody wants to write any answer i close this topic, assuming that a maximum of 10 users or so can be supported using swellrt and turn to other technologies spreading my text (e.g. video transmission)... 
any last comments?

**Comment by pablojan** [comment]
Hi, sorry for answering so late,

First, from  SwellRT's server perspective there is no differences whether
the client reads only or write to the document, each client will open a
websocket and write metadata* under the hood.
So, first thing to consider is how many websockets connections will support
Jetty.
Secondly, for each connection, the server will handle views of the
considered documents (in Wave terms, wavelets views). So it would be
necessary to meause how much heap memory takes each connection's views.
Finally, to support high concurrecy level, server's thread settings should
be tweak.

*for this particular case, we could avoid to send any metadata to the
server for the only read clients, it could relieve servers load.

2018-06-11 22:05 GMT+02:00 haraldjordan78 <notifications@github.com>:

**Comment by haraldjordan78** [comment]
Hey Pablo,
thanks for your reply :-)
Sure i already had a think about how to avoid to send any metadata from the client, but even if i am already able to work on the source code and build new versions, currently i don't stand any chance to get out how this could possibly be done. 
What would be your first try? :-)

cheers,
Harald

**Comment by haraldjordan78** [comment]
Problem is too fuzzy to grep yet, working on server stability in https://github.com/P2Pvalue/swellrt/issues/243
