### ISSUE TITLE
Server messages are not handle by Wave client after reconnect to server

### ISSUE THREAD

**Issue by pablojan** [P2Pvalue/swellrt#24]
After a reconnect, client can keep sending messages to the server but ack's are not processed by client. They got the Atmosphere client but it seems they are not handle properly by WaveWebSocketClient

**Comment by pablojan** [comment]
Wave protocol connections can't be resumed on following conditions:

- On Server reboot -> the client will send wave messages with a seqNumber > 0 but server's will expect a seqNumber = 0;

- On http session expiration

- On network disconnection (1) 

Atmosphere doesn't handle properly error messages (response.sendError) on remote client side, so we can't handle these conditions in the app.

This could be resolved (except 1) sending app-level messages (response.output(myErrorMsg)) and then process them by the Wave protocol connection layer.

**Comment by atd** [comment]
Is it possible that in case 1, the server would send an error message and the client would reconnect?

**Comment by pablojan** [comment]
Did you mean "On network disconnection"? in that case, Atmosphere returns a 408 status, we can try to reconnect from the app layer.

**Comment by atd** [comment]
Sorry, but I don't understand the issue.

Are wave connections going to be resumed?

**Comment by pablojan** [comment]
These comments apply to the Atmosphere layer limitations (which encapsulates WebSocket/HTTP transports). Hence, in these three situations, the Wave protocol layer should take the responsability to resume the Wave connection. This is not implemented yet, but the SwellRT API provides callbacks to inform apps about when the connection is closed.

**Comment by atd** [comment]
Ok, I understand now

Indeed, as a SwellRT user, I expect the Wave protocol reconnecting for me.

I don't know if there is an issue about the forthcoming implementation. Just for reference
