### ISSUE TITLE
Rich text editor diffs display: erased text not propertly shown

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/swellrt#27]
SwellRT editor shows the differences between the last time you visited the text and the current version:
* In yellow background new text
* with a weird grey box, the erased text.

This grey box is unexpected, while the diff functionality is not really important in this phase of development. Please consider to remove the diff functionallity or fix the way erased text is displayed.

**Comment by atd** [comment]
It should just mark the related `<div>` with a class, and let app developers to give style to those divs

That functionality would be enough for us (we can hide divs with css)
