### ISSUE TITLE
openModel callback is overriden when several calls are done

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/swellrt#31]
Executing following code, the obtained result is 'bar' 'bar' while the expected result is either 'foo', 'bar' or 'bar', 'foo' (each callback called once).

```
window.SwellRT.openModel(
  waveId1,
  function(model) {
    console.log('foo');
  });
window.SwellRT.openModel(
  waveId2,
  function(model) {
    console.log('bar');
  });
```

**Comment by pablojan** [comment]
Did you add a test case for it?

**Comment by atd** [comment]
Tests tests tests!!!

:dancers: :dancers: :dancers:

**Comment by pablojan** [comment]
Despues de liarla hoy un poco he subido una nueva version con tests para
esto. ;)

**Comment by atfornes** [comment]
Thanks, and sorry for not noticing the conflict with #23

**Comment by pablojan** [comment]
Very welcome. It wasn't your fault, I did a mess when I merged your changes
;)

2015-07-03 17:30 GMT+02:00 atfornes <notifications@github.com>:
