### ISSUE TITLE
SwellRT version

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#32]
Add support for SwellRT version

Ideally, it should be shown with a command, like:

```shell
$ ant version
0.5.1
```

**Comment by pablojan** [comment]
Ant always shows junky text. The cleanest way to make this is something like this:
Is it good to you?

```
pablojan@lemovo-pc:~/Development/projects/wave-mod$ ant -f build-swellrt.xml version
Buildfile: /home/pablojan/Development/projects/wave-mod/build-swellrt.xml

version:
     [echo] Version=0.1.0-alpha

BUILD SUCCESSFUL
Total time: 0 seconds
```

**Comment by atd** [comment]
Sure! It can work

I can just parse the output and use what is behind `[echo] Version=`

**Comment by pablojan** [comment]
Ready!

**Comment by atd** [comment]
Awesome! Thank you

2015-07-01 13:48 GMT+02:00 Pablo Ojanguren <notifications@github.com>:
