### ISSUE TITLE
Bind to 0.0.0.0

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#35]
Let jetty to bind to every network interface and any host name

**Comment by atd** [comment]
Using 0.0.0.0 as proposed in several sites, requires a hostname of `0.0.0.0`

Maybe updating jetty will solve the issue?

**Comment by pablojan** [comment]
@atd Commited in master 0.4.0-alpha (not tagged)

**Comment by atd** [comment]
Awesome!! :clap: :clap: 

@pablojan note that if the version is changed but not tagged, the docker image will be built

Maybe we want to change for the tag to build the docker image

If so, please let me know

**Comment by pablojan** [comment]
I would prefer to test the feature (you to test it) before tagging it. 

With which version the docker image is built?

**Comment by atd** [comment]
It is built from the first commit that changes `build-swellrt.properties`

In this case, it is been built from https://github.com/P2Pvalue/swellrt/commit/b1c20d18d3ee5b46cd3489a7265484118fffa4c3

We should change the behavior then, shouldn't we?
