### ISSUE TITLE
debugger in swellrt.js

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#39]
Maybe we can get rid of this `debugger` sentence in SwellRT

```js
function getAssertionsOn(){
  try {
    debugger;
    throw makeAssertionError();
  }
   catch ($e0) {
    $e0 = wrap($e0);
    if (instanceOf($e0, Q$AssertionError)) {
      $e0;
      return true;
    }
     else 
      throw unwrap($e0);
  }
  return false;
}
```

It usually pops up while developing pear2pear

**Comment by atd** [comment]
:pray: :pray: :pray:

**Comment by pablojan** [comment]
It shows up in only in Chrome when debug console is open. Is this true for you?

**Comment by atd** [comment]
Yes, but it is a real pain in the ass when developing Pear2Pear, because you have developer console open, and every single change you do, you have to click the continue button

**Comment by atd** [comment]
I can count the times I click in the damn play button today, and tell you if you want

**Comment by pablojan** [comment]
Note: this is triggered on editor load!

2015-08-05 9:50 GMT+02:00 Antonio Tapiador <notifications@github.com>:

**Comment by atd** [comment]
I know, I am working on the pad title reminder

15 times so far

**Comment by pablojan** [comment]
I am working on it! it was just a personal note! :D

2015-08-05 10:54 GMT+02:00 Antonio Tapiador <notifications@github.com>:

**Comment by atd** [comment]
Ok, I though all you had to do was removing that line.

I am sorry for being so boring but, believe me, it is really annoying to go to see your changes and finding the execution of the browser paused. Besides, it is harder to click the play button in mobile view

**Comment by pablojan** [comment]
The issue is with the compilation mode of SwellRT JS API.

In Jenkins we are using task "dist-dev". This produces pretty JS code (no
production), good to debug on browsers, but it also has activated the
assertion control.
I am going to modify this task to deactivate assertions. To which
branch/version do you want to have this change performed?


2015-08-05 11:03 GMT+02:00 Antonio Tapiador <notifications@github.com>:

**Comment by atd** [comment]
The one used by angular-swellrt

Thank you Pablo!

2015-08-05 11:50 GMT+02:00 Pablo Ojanguren <notifications@github.com>:

**Comment by pablojan** [comment]
swellrt-angular is using v0.6.0-alpha
Changes deployed in v0.6.4-alpha

Is it ok? can you update from 0.6.0 to 0.6.4?


2015-08-05 11:56 GMT+02:00 Antonio Tapiador <notifications@github.com>:

**Comment by atd** [comment]
Sure! Thank you very much

2015-08-05 13:13 GMT+02:00 Pablo Ojanguren <notifications@github.com>:
