### ISSUE TITLE
SwellRT.query error when first parameter in the string form contains a wave id  

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/swellrt#41]
I expect the following two queries to be equivalent, however, the second produces an error, am I doing something wrong?:

- parameter in JSON format:
```javascript
  var id = 'local.net/s+VPmCWEf0GGA';
  SwellRT.query({'root.id': id}, function(res){console.log(JSON.stringify(res))})
```
- parameter in string format:
```javascript
  var id = 'local.net/s+VPmCWEf0GGA'
  SwellRT.query("{'root.id': " + id + "}", function(res){console.log(JSON.stringify(res))})
```

Last form produces the following error GET http://swellrt:9898/swell/model?q=%7B%27root.id%27%3A+local.net%2Fs%2BVPmCWEf0GGA%7D 500 (Server Error)

maybe the problem is related with escaped characters in the URL?

**Comment by pablojan** [comment]
Not an issue. Add '' around the id var in the second expression.

**Comment by atfornes** [comment]
Thanks! the correct expression is:
```javascript
("{'root.id': '" + id + "'}"
```
