### ISSUE TITLE
Pad issues in Android 5

### ISSUE THREAD

**Issue by pablojan** [P2Pvalue/swellrt#42]
Android 5 - Fefault browser: 
    Bad focus and auto-write words

Android 5 - Chrome
    After entering a word in the collaborative editor, in the pad, the keyboard is hidden.

IPad OSX 7.1.1- Safari 
    Accepting 3rd party cookies must be enabled on Safari preferences. It still took quite time to load  
   but it works

**Comment by pablojan** [comment]
Android WebKit (+4.4) -> key events doens't work (key code always 0). More info:

http://code.google.com/p/android/issues/detail?id=68858
http://stackoverflow.com/questions/11429878/read-keyboard-events-in-android-webview

https://code.google.com/p/android/issues/detail?id=42904#c15

**Comment by pablojan** [comment]
Android >4.4 Webview doesn't work with original composition event handler.
http://techblog.open-xchange.com/2014/12/02/android-chrome-and-composition-events/

A new composition events handler must be developed for Mobile Chromiun

**Comment by atfornes** [comment]
:clap: :clap: :clap:

**Comment by atd** [comment]
Yayyyy!!!!

May we have a tagged version so we update Pear2Pear? :-)

2015-10-31 10:35 GMT+01:00 atfornes <notifications@github.com>:
