### ISSUE TITLE
Swellrt.org pad does not load with Firefox

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/swellrt#49]
I have issues accessing the pad at swellrt.org with firefox, while I do not have those issues neither accessing [pear2pear app](p.p2pvalue.eu) pad nor accessing the pad at swellrt.org with chromium.

I do not have the issue neither accessing with chromium.

Here I copy the browser log:

message | code line
-------------|-----------
Session started |  /swellrt/ (línea 381)
Atmosphere Connection Close 501 |                                   atmosphere.js (línea 2898)
Network disconnected null              |                                    /swellrt/ (línea 367)
Atmosphere callback 501                |                                    atmosphere.js (línea 2898)
Websocket failed. Downgrading to Comet and resending |  atmosphere.js (línea 2898)
Atmosphere Connection Transport Failure Websocket failed. Downgrading to Comet and resending |

**Comment by pablojan** [comment]
Please provide Firefox version. Thanks

2015-08-06 11:47 GMT+02:00 atfornes <notifications@github.com>:

**Comment by atfornes** [comment]
Sure, Firefox version is 39.0

**Comment by atd** [comment]
@atfornes Do you see the same requests as in #52 ?

**Comment by atfornes** [comment]
yes, I have a screenshot of the Headings and answers of the request, but dont know how to add it here ...

**Comment by pablojan** [comment]
See #54
