### ISSUE TITLE
Bug with keyboard imputs : Can't move in the textarea in keyboard.

### ISSUE THREAD

**Issue by Manu1400** [P2Pvalue/swellrt#50]
On my Ubuntu VM (a virtual machine) on VDI with Google Chrome browser : 

1/ Go to http://p2pvalue.github.io/swellrt/
2/ Add 'a.' string in the textarea.
3/ Press the '<=' key on your keyboard. The cursor moved between 'a' and '.' chars.
4/ Press the '=>' key on your keyboard do nothing.

Bug too with 'a!' string.

I don't have this bug with Mozilla Firefox.

FYI, i have sometime problems with a keyboard on VDI.

**Comment by Manu1400** [comment]
I don't have errors in web console.

**Comment by Manu1400** [comment]
In chrome://extensions/ : developper mode and extensions is not actived

**Comment by pablojan** [comment]
Thank you reporting the issue.
Are you adding the text at the end of the the textarea?


2015-08-06 12:25 GMT+02:00 Manu1400 <notifications@github.com>:

**Comment by Manu1400** [comment]
I disabled the spell checker but the bug is always here.

**Comment by Manu1400** [comment]
Yes ! I have the bug only when i add the text at the end of the textarea.
>Are you adding the text at the end of the textarea?

**Comment by pablojan** [comment]
Thanks!

2015-08-06 12:42 GMT+02:00 Manu1400 <notifications@github.com>:

**Comment by Manu1400** [comment]
A other keyboard/chars bug : #51

**Comment by Manu1400** [comment]
Do you need some others tests / informations ?

**Comment by pablojan** [comment]
The more browser+platforms tested the better!


Also, any communications problem is good to be aware of.
You can see comms log messages in browser's console.

Thanks a lot!

2015-08-06 13:49 GMT+02:00 Manu1400 <notifications@github.com>:

**Comment by pablojan** [comment]
I can't reproduce this issues exactly in my (Ubuntu) Chrome 35.0.1916.114 (Build oficial 270117) 
Would you mind to provide versions plz?

Thank you

**Comment by pablojan** [comment]
Please, could you test fix in swellrt.org? Thank you

**Comment by Manu1400** [comment]
It's OK.
