### ISSUE TITLE
Bug with the char '&'

### ISSUE THREAD

**Issue by Manu1400** [P2Pvalue/swellrt#51]
On Google Chrome : 

1/ With your keyboard, enter 'a&²'

Excepted : see 'a&²' string on the textarea

Actual : display 'a²&'

**Comment by atd** [comment]
Also with `(`

It seems the pad doesn't like special chars

**Comment by pablojan** [comment]
Please test in swellrt.org 
Only fixed #50. 
#51 needs deeper research and it doesn't have priority.

**Comment by Manu1400** [comment]
string 'a&²' => works !

**Comment by pablojan** [comment]
Please be careful, I think it doesn't work everytime.
Thanks for your feedback.
