### ISSUE TITLE
demo pad not clickable in chromium

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#52]
The demo pad is not clickable in chromium

console output:

```
Session started
atmosphere.js:2898 Atmosphere Connection Close 501
(index):367 Network disconnected null
atmosphere.js:2898 Atmosphere callback 501
atmosphere.js:2898 Websocket failed. Downgrading to Comet and resending
atmosphere.js:2898 Atmosphere Connection Transport Failure Websocket failed. Downgrading to Comet and resending
atmosphere.js:2898 Atmosphere Connection Open
(index):342 Network connected
atmosphere.js:2898 Atmosphere callback 200
```

Chromium version is 44.0.2403.107

**Comment by atfornes** [comment]
Weird, I have the same issue with Firefox but not with chromium https://github.com/P2Pvalue/swellrt/issues/49

**Comment by atd** [comment]
Atmosphere keeps sending the request `http://demo.swellrt.org/atmosphere?X-Atmosphere-tracking-id=eb7bf3ae-c254-46d3-ab64-67de4938cce3&X-Atmosphere-Framework=2.1.5-javascript&X-Atmosphere-Transport=long-polling&X-Atmosphere-TrackMessageSize=true&X-Cache-Date=0&X-atmo-protocol=true&_=1438858420541` every 10 ms or so

**Comment by pablojan** [comment]
See #54
