### ISSUE TITLE
Show other participant's cursors in pad

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#61]
When two people are editing a text at the same time, suddenly some characters appear, like magic. It would help to know someone is editing the text, and where is s/he

**Comment by pablojan** [comment]
V0.7.0 provides a basic highlighting of others text

**Comment by atd** [comment]
Ok, I will check if it is enough. Currently, I cannot see such highlighting

**Comment by atd** [comment]
After experiencing highlighting, I still wish I was able to recognize who is writing that highlighted text

**Comment by pablojan** [comment]
This is implemented in beta version, but unfortunately not in alpha.
