### ISSUE TITLE
Arrays mutations doesn't work

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#94]
When adding new messages from phone, in desktop they appear empty. After reloading the wave, they appear right

**Comment by pablojan** [comment]
When an array item is added, remote participants get an empty mutated item and the wavelet view gets inconsistent. Further changes from a remote participant are ignored

**Comment by pablojan** [comment]
It might be not a bug, please check your code for following:

* Documentation about event listener for arrays is wrong. The event listener will receive one only array as parameter on and ITEM_ADDED event:

```
_array.registerEventHandler(SwellRT.events.ITEM_ADDED, 
function(arg) { 
// arg is an array
arg[0]; // the index of new item in the array
arg[1]; // the new object
arg[2]; // (optionally) the old object in that index
});
```

* Adding a new map to an array produces a ITEM_ADDED event with an empty map. This can explain this issue.

```
// 1) Paricipant A  adds a new Map to the array
_map = _array.add(_model.createMap()); //
_map.put("key", _model.createString("Hello World");

// 2) Participant B receive a ITEM_ADDED event with following argument:
arg[0] // Index of new item (the map)
arg[1] // The map object, without any field yet


```

**Comment by atd** [comment]
I guess this is an angular-swellrt issue then? @atfornes

**Comment by pablojan** [comment]
I also have checked the mutation event listener on maps and they are working normally. These are the steps I made:

1) Participant A create a model with an 'array' and shares it with Participant B
2) B register a listener for new items in 'array'
3) A add a new map 'map1' into the 'array'. Listener on B is triggered for new item 'map1'.
4) B register a lister for new items and changed items on 'map1'
5) A adds new pair  key,value on 'map1'. Listener on B is triggered for new 'map1.key'

**Comment by atfornes** [comment]
I will check angular-swellrt for this problems

**Comment by atfornes** [comment]
I have research on this further.

It seems to be a race condition or asynchronous management problem. The following code reproduces the issue:

* Open a client and login with an user `user1` and execute the following code:
```javascript
var mod;
var list;
SwellRT.createModel(function(m){
  mod = m;
  list = mod.createList();
  mod.root.put('list', list);
  mod.addParticipant('user2@local.net');
})
```

* Open a different client and login with `user2` and run the following code:

```javascript
var list;
SwellRT.openModel('use_wave_address_previously_created', function(mod){
  list = mod.root.get('list');
  console.log('list', list);
  list.registerEventHandler(
    SwellRT.events.ITEM_ADDED,
    function(i){
      console.log('list item added', i);
      i[1].registerEventHandler(
        SwellRT.events.ITEM_ADDED,
        function(field){
          console.log('object field added', field[0], field[1]);
        });
    });
});
```

* With the first client copy and execute the following code (copy and execute all lines, not one by one)
```javascript
var map1 = mod.createMap();
var value1 = mod.createString('value1');
list.add(map1);
map1.put('key1', value1);
```
*Unexpected behavior!!* in client 2 you will se only a log of the list item added similar to `list item added ["0", Object]`

* With the first client copy and execute the following code (copy and execute all lines, not one by one)

```javascript
var map2 = mod.createMap();
var value2 = mod.createString('value2');
list.add(map2);
setTimeout(function(){
  map2.put('key2', value2);
}, 1000);
```

*Correct Behavior:* This code is equivalent (except for the timeout waiting) to previous one, but in the second client you will see the expected logs: `list item added` and `object field added`

Furthemore, if you copy the previous two fragment codes and execute togheter, only the first list item added will be logged.

I have done a git bisect and apparently the first wrong commit is ed89f8c (previous 4 did not compile)

**Comment by pablojan** [comment]
It seems that mutations on the XML document (the underlying map storage) are not received in the client in the right order,

```
(map+LNpLxYNA9oB) Doc Event CI:<entry k="keyV2" v="str+0"></entry>
(map+LNpLxYNA9oB) Doc Event CI:<i v="valueV2"></i>
```
in this case, we can't retrieve actually the value "valueV2" (str+0) when the map entry is updated. The fix take this into account to trigger map events when all info has been received.

**Comment by pablojan** [comment]
Plz @atfornes could you test it on teem? thanks
