### ISSUE TITLE
Review timeout policy on SwellRT callbacks

### ISSUE THREAD

**Issue by pablojan** [P2Pvalue/swellrt#95]
Opened as answer to https://github.com/P2Pvalue/swellrt/issues/93

**Comment by atd** [comment]
Do those timeout rise an error?

**Comment by pablojan** [comment]
During invocation of createModel() or openModel() two networks operations occurs:

* First a http get request. this can raise a timeout exception captured in the failure callback of the createModel() or openModel().

* Secondly, wavelet's initial data must be delivered to the websocket. In this case, a time out exception on the websocket will be deliver through the global event handler as a SwellRT.events.FATAL_EXCEPTION.

This issue's intent is to provide consistency regarding this behaviour.

**Comment by pablojan** [comment]
Caused by the currently removed request access operation
